FEAT:List User
Ponhrith/Task2-ID pull request #4
Opened 2022-09-14 08:00 UTC by Ponhrith

-readData function use bufferedReader
-use loop to read the line and print

2022-09-14 08:34 UTC, VandyTheCoder reviewed
Please resolve my comment before request to review again.

2022-09-14 08:34 UTC, VandyTheCoder commented on ID/src/main/kotlin/helper/FileHelper.kt
> +    fun readData(file: File){
It kinda not friendly after printing data.
Please enhance it.

2022-09-19 07:15 UTC, Ponhrith commented
-Create option for users
-Pad the table using StringBuilder

2022-09-19 09:16 UTC, VandyTheCoder requested changes
Please resolve my comments.

2022-09-19 09:16 UTC, VandyTheCoder commented on ID/src/main/kotlin/Table/TableOutput.kt
> +class TableOutput {
Please remove this file, if it is not used.

2022-09-19 09:16 UTC, VandyTheCoder commented on ID/src/main/kotlin/helper/FileHelper.kt
> +    fun checkOptionsWhenStart(file: File){
I think this method should in other Class. Something like main screen.
It is option to interact with user. So it will identify as screen class.

2022-09-19 09:16 UTC, VandyTheCoder commented on ID/src/main/kotlin/model/Person.kt
> +        fun getAgeFromInput() : Int {
Group this method to use it dynamic.

2022-09-19 09:16 UTC, VandyTheCoder commented on ID/src/main/kotlin/screen/UserScreen.kt
> +        print("Put 'q' to quit and put any keys to continue insert user: ")
In print, message.
Put any keys to continue to insert user, it should change to put any keys to back to main menu.

2022-09-20 08:42 UTC, VandyTheCoder approved these changes

2022-09-20 08:42 UTC, merged